### ISSUE TITLE
WARNING: LightTable.jl: cannot resize array with shared data

### ISSUE THREAD

**Issue by MikaelSlevinsky** [one-more-minute/Jewel.jl#30]
```julia
WARNING: LightTable.jl: cannot resize array with shared data
 in push! at ./array.jl:430
 in read_operator at /Users/Mikael/.julia/v0.4/JuliaParser/src/lexer.jl:368
 in next_token at /Users/Mikael/.julia/v0.4/JuliaParser/src/lexer.jl:752
 in qualifiedname at /Users/Mikael/.julia/v0.4/Jewel/src/parse/scope.jl:59
 in nexttoken at /Users/Mikael/.julia/v0.4/Jewel/src/parse/scope.jl:78
 in tokens at /Users/Mikael/.julia/v0.4/Jewel/src/parse/scope.jl:178
 in allcompletions at /Users/Mikael/.julia/v0.4/Jewel/src/completions.jl:72
 in anonymous at /Users/Mikael/.julia/v0.4/Jewel/src/LightTable/completions.jl:5
 in handlecmd at /Users/Mikael/.julia/v0.4/Jewel/src/LightTable/LightTable.jl:65
 in handlenext at /Users/Mikael/.julia/v0.4/Jewel/src/LightTable/LightTable.jl:81
 in server at /Users/Mikael/.julia/v0.4/Jewel/src/LightTable/LightTable.jl:22
 in server at /Users/Mikael/.julia/v0.4/Jewel/src/Jewel.jl:18
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
```

MWE with this version of Julia:
```julia
julia> versioninfo()
Julia Version 0.4.0-rc1+33
Commit a0fa6af* (2015-09-13 16:27 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
and on the master branches of Julia-LT, Juno-LT, Jewel.jl, JuliaParser.jl, LNR.jl, and Lazy.jl, I open LightTable, and in the default Tutorial.jl file, I type `a`, then delete it.

**Comment by dangjc** [comment]
I traced this down to JuliaParser: jakebolewski/JuliaParser.jl#26.

**Comment by Zwei1666** [comment]
Can this issue be closed as this bug in JuliaParser was fixed?

**Comment by MikaelSlevinsky** [comment]
Yes it works, thank you!

**Comment by Andy-P** [comment]
I just update Julia using the window.exe 64 link
https://s3.amazonaws.com/julialang/bin/winnt/x64/0.4/julia-0.4.0-win64.exe

But I am still getting this problem. Version too old?

Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by JoanneChew** [comment]
Hi, I am not a techsavvy. I have the same problem of "LightTable.jl: cannot resize array with shared data". I know this problem has been solved but how do I actually get rid of this problem in my LT?

I downloaded Julia, Juno/LT about a week ago. I do not have any pull request. I am confuse and need some help. 

Thank you

**Comment by gdziadkiewicz** [comment]
@Andy-P 
I just tried to reproduce your problem on my environment and did not succeed. I managed to install Julia using link provided by you and get Juno running with steps from  http://junolab.org/docs/install-manual.html. I listed potential problems you may be facing and are worth checking. 

@JoanneChew 
Can you check the listed problems and solutions?

##### Possible problems:
1. You installed Juno using the bundle package from Juno website which contains it's own Julia copy. In this case updating the new Julia, installed from the link, won't help. The solution is to change path to the new Julia in Juno (section Setting Julia path in [link](http://junolab.org/docs/install-manual.html)).
2. You did not use Pkg.update() to update packages and your JuliaParser package is still old. The solution is to run it.
 
If none of those help please provide output from running Pkg.status() in your Julia installation.

**Comment by MikaelSlevinsky** [comment]
@JoanneChew, it looks like @gdziadkiewicz has some solid advice. But in case this is useful to you, this worked for me on Mac OS X. In Terminal, run
```
cd ~/Library/Application\ Support/LightTable/plugins/
rm -rf Julia
rm -rf Juno
git clone https://github.com/one-more-minute/Julia-LT.git
git clone https://github.com/one-more-minute/Juno-LT.git
mv Julia-LT Julia
mv Juno-LT Juno
```
followed in Julia by:
```julia
Pkg.checkout("Jewel"); Pkg.checkout("JuliaParser")
Pkg.checkout("LNR"); Pkg.checkout("Lazy")
```
After doing this once, the Terminal part can be replaced by:
```
cd ~/Library/Application\ Support/LightTable/plugins/Julia
git pull
cd ~/Library/Application\ Support/LightTable/plugins/Juno
git pull
```
